Repository python-semver/python-semver, pull requests merged in 2020-10, with the labels that each got.

#277 Turn VersionInfo.parse into classmethod to allow subclasses
  semver.py
  test_semver.py
Labels: Blocked, enhancement

#286 Add author and update changelog for #276/#277
  CHANGELOG.rst
  CONTRIBUTORS
Labels: doc

#275 Fix #274: String Types Py2 vs. Py3 compatibility
  CHANGELOG.rst
  CONTRIBUTORS
  docs/usage.rst
  semver.py
  setup.cfg
  test_typeerror-274.py
Labels: Release_2.x.y, bug

#292 Fix #291: Disallow negative numbers in VersionInfo
  CHANGELOG.rst
  docs/usage.rst
  semver.py
  test_semver.py
Labels: Release_2.x.y, Release_3.x.y, bug

#294 Prepare 2.12.0 release (#293)
  semver.py
Labels: Release_2.x.y

#283 Ensure equal versions have equal hashes
  docs/usage.rst
  semver.py
  test_semver.py
Labels: enhancement

#287 Document how to create subclass from VersionInfo
  conftest.py
  docs/semverwithvprefix.py
  docs/usage.rst
  setup.cfg
  test_semver.py
Labels: doc

#295 Prepare 2.13.0 release
  CHANGELOG.rst
  CONTRIBUTORS
  semver.py
Labels: Release_2.x.y, Release_3.x.y, bug

#296 Support latest Python version for semver2
  .travis.yml
  README.rst
  setup.py
  tox.ini
Labels: infra
