Repository python-semver/python-semver, pull requests merged in 2020-06, with the labels that each got.

#263 Doc: Add missing "install" for openSUSE
  docs/install.rst
Labels: bug, doc

#268 Increase coverage
  test_semver.py
Labels: enhancement

#272 Prepare 2.10.2 release (#271)
  CHANGELOG.rst
  semver.py
Labels: Release_2.x.y
