Repository python-semver/python-semver, pull requests merged in 2023-04, with the labels that each got.

#401 Simplify max_ver and min_ver
  src/semver/_deprecated.py
Labels: Release_3.x.y, Enhancement

#402 Fix #258: Keep semver._deprecated.compare
  CHANGELOG.rst
  docs/api.rst
  docs/changelog-semver2.rst
  docs/conf.py
  docs/index.rst
  docs/inventories/python-objects.inv
  docs/usage/compare-versions.rst
  src/semver/__init__.py
  src/semver/_deprecated.py
  tests/test_deprecated_functions.py
Labels: Release_3.x.y, Enhancement, Design

#403 Build 3.0.0 release of semver
  docs/usage/semver-version.rst
  src/semver/__about__.py
Labels: Release_3.x.y

#405 Remove incorrect dependencies from build-system section of pyproject.toml
  pyproject.toml
  tox.ini
Labels: Release_3.x.y, Infra

#406 correct typo in function description of `next_version`
  src/semver/version.py
Labels: Enhancement

#409 Add CITATION.cff for citation
  CITATION.cff
  release-procedure.md
Labels: Infra
