Repository python-semver/python-semver, pull requests merged in 2025-01, with the labels that each got.

#459 Fix 3.0.3
  CHANGELOG.rst
  MANIFEST.in
  docs/usage/semver-version.rst
  pyproject.toml
  src/semver/__about__.py
Labels: Bug

#464 Fix #463: Remove duplicate code Version.bump_build
  changelog.d/463.trivial.rst
  src/semver/version.py
Labels: Enhancement

#462 Fix #460 Improve bump_prerelease to alway get a newer version
  changelog.d/460.bugfix.rst
  docs/usage/raise-parts-of-a-version.rst
  src/semver/version.py
  tests/test_bump.py
  tests/test_pysemver-cli.py
  tox.ini
Labels: Release_3.x.y, Bug
